### ISSUE TITLE
How to show only main domain on URL?

### ISSUE THREAD

**Issue by aldricha** [rNeomy/reader-view#116]
Hi there. I'm wondering if it is possible using CSS to have the reader view show only the main URL domain instead of the entire link? For instance, if reading a NYTimes article, how do I change it so that the URL at the top shows only "nytimes.com" instead of the full URL? Thanks!

**Comment by rNeomy** [comment]
Try to append the following to the "Custom styling (reader view)" section of the options page.

```css
#reader-domain > span:last-of-type {
  display: none;
}
```
