### ISSUE TITLE
Can you improve the printout? thank you

### ISSUE THREAD

**Issue by zhl111** [rNeomy/reader-view#149]
![image](https://user-images.githubusercontent.com/29135984/197468594-959b5d91-612a-4e35-9175-67e994a5818e.png)

**Comment by rNeomy** [comment]
Thanks for the report. The extension was supposed to remove the theme for the print view. For now, append the following CSS to the "Custom Styling" section of the options page.

```css
@media print {
  body {
    --fg: #000 !important;
    --bd: #000 !important;
    --bg: #fff !important;
  }
}
```

**Comment by rNeomy** [comment]
The `0.6.7` release has an improved print layout using the following CSS code:

```css
@media print {
  body[data-mode] {
    --fg: #000;
    --bd: #000;
    --bg: #fff;

    width: unset;
    padding: 0;
    margin: 0;
  }
}
```
Just set the `Margins` to the default value, and you will get a clean margin on all sides. Since this is not a perfect solution, I'll keep this open for code suggestions.
