### ISSUE TITLE
[Question] Any way to expand the image width to the full body size?

### ISSUE THREAD

**Issue by craziedde** [rNeomy/reader-view#212]
Hi,

### Question in the screenshot below:

![Image](https://github.com/user-attachments/assets/b5d30329-8f77-44f8-9c09-c90e00c7e642)

**Comment by mycroft89** [comment]
I'm on the same boat. How do I accomplish that?

I tried adding some custom CSS like:

```
img {
  max-width: 100% !important;
  height: auto !important;     
  display: block !important;  
}
```

(Courtesy of an LLM)

Still doesn't work.

**Comment by craziedde** [comment]
Hi @mycroft89 

# This actually worked for me

```css
body {
/*** Ed **/
  padding-bottom: 64px;
  font-size: 16px !important;
  font-family: Helvetica, Arial, sans-serif;
  color: black;
  width: 95% !important;
  background-color: white;
/*** Ed **/
}

/** Ed resize images to full width **/
img {
  width: 100% !important;
  height:auto !important;
}
``` 

---
# My Full settings

<img width="1060" height="2370" alt="Image" src="https://github.com/user-attachments/assets/701399ca-4a3e-4dac-baee-4c3536933c36" />

**Comment by mycroft89** [comment]
@craziedde It doesn't seem to work really. If you check out carefully, you'll see that despite the text taking almost the entire width of the screen and images being super visible, they still don't reach the actual margins of the text. :-/

**Comment by craziedde** [comment]
@mycroft89 

I apologize; real life kept me a little busy.
Here is the fix for your issue

```CSS
body {
  padding-bottom: 64px;
}

figure {
    margin-block-start: 0px !important;
    margin-block-end: 0px !important;
    margin-inline-start: 0px !important;
    margin-inline-end: 0px !important;
}

/** Ed resize images to full width **/
img {
  width: 100% !important;
  height:auto !important;
}

pre {
  white-space: pre-wrap;
}
pre code {
  background-color: #eff0f1;
  color: #393318;
  font-family: monospace;
  display: block;
  padding: 5px 10px;
  overflow: hidden;
}
blockquote {
  padding: 0;
  padding-inline-start: 2ch;
  border-inline-start: 2px solid var(--bd);
}
aside {
  color: color-mix(in srgb, var(--fg), var(--bg) 20%);
}
body[data-mode="dark"] pre code {
  background-color: #eff0f1;
  color: #393318;
}

/* CSS for sans-serif fonts */
body[data-font=sans-serif] {}
/* CSS for serif fonts */
body[data-font=serif] {}

/* CSS for "sepia" theme */
html[data-mode=sepia] {}
/* CSS for "light" theme */
html[data-mode=light] {}
/* CSS for "dark" theme */
html[data-mode=dark] {}
```
