### ISSUE TITLE
Feature request: support code formatting in reader view

### ISSUE THREAD

**Issue by userlond** [rNeomy/reader-view#25]
For example: http://docs.guzzlephp.org/en/stable/, https://github.com/sima-land/api-php-client/blob/master/doc/client.md.

Just idea, we may preserve styles of block with `highlight` class (or add setting to set css selectors of blocks, where we must preserve site styles). Or simply, preserve spaces and set monospace font in `pre` blocks.

**Comment by userlond** [comment]
Found "Custom styling" feature, seems like some tweaks are ok to see code perfectly:

``` css
pre, code {
  white-space: pre-wrap;
  font-family: 'Courier New', monospace;
  font-size: 80%;
}
/* CSS for "light" theme */
body[data-mode=light] pre, body[data-mode=light] code {
  background-color: #fafafa;
}
```
