### ISSUE TITLE
Feature Request: blur top and bottom

### ISSUE THREAD

**Issue by shand-obs** [rNeomy/reader-view#37]
I like to _see_ text I've already read or that is upcoming and have the area I am actively reading in the center of my screen (vertically). I switch between screens often though and often lose my place when I'm reading.

I would like to have a feature where the top and bottom of the window is _blurred_ or washes out as it moves away from the center to the top or bottom of the window. This way I can scroll the text such that the area I am actively reading is inside the non-blurred area and is easy to find when my attention returns from another screen.

**Comment by rNeomy** [comment]
use the following CSS code in the options page:
```css
body:after {
    pointer-events: none;
    content: '';
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background: linear-gradient(to bottom, rgba(0,0,0, 0.3) 0%,rgba(0,0,0, 0.3) 33%,transparent 33%,transparent 66%,transparent 65%,rgba(0,0,0, 0.3) 66%,rgba(0,0,0, 0.3) 100%);
}
```
